In [1]:
import numpy as np


def SwapRow(matt, i1, i2):
    if i1 == i2:
        return
    row1 = matt[i1].copy()
    matt[i1] = matt[i2]
    matt[i2] = row1
    return


def FindNonZeroRow(matt, n, iRow, iCol):
    for i in range(iRow, n):
        if matt[i][iCol] != 0:
            return int(i)
    return int(-1)


def ToGauss_JordanForm(matt, n):
    iRow = 0
    iCol = 0
    while iRow < n and iCol < n:
        nonZr = FindNonZeroRow(matt, n, iRow, iCol)
        if nonZr == -1:
            iCol += 1
        else:
            SwapRow(matt, iRow, nonZr)
            factor = matt[iRow][iCol]
            matt[iRow][iCol] = 1
            for i in range(iCol + 1, n + 1):
                matt[iRow][i] /= factor
            for i in range(n):
                if i == iRow:
                    continue
                else:
                    fact = matt[i][iCol]
                    for j in range(iCol, n + 1):
                        matt[i][j] -= matt[iRow][j] * fact
            iCol += 1
            iRow += 1
    return matt


def Rank(matt, rWall):
    n = len(matt)
    r = 0
    for i in range(n):
        for j in range(n + 1 - rWall):
            if matt[i][j] != 0:
                r += 1
                break
    return r


def FindSolutions(matt, n):
    ToGauss_JordanForm(matt, n)
    sols = ["" for _ in range(n)]
    rA = Rank(matt, 0)
    rB = Rank(matt, 1)
    if rB < rA:
        return "vo nghiem"
    if rB == rA and rA == n:
        print("1 nghiem")
        sols = ["x" + str(i + 1) + " = " + str(matt[i][n]) for i in range(n)]
        return sols
    else:
        deg = 0
        for i in range(n):
            lead = -1
            for j in range(n):
                if matt[i][j] != 0:
                    if lead == -1:
                        lead = j
                        sols[lead] = str(matt[i][n]) + " "
                    else:
                        if sols[j] == "":
                            sols[j] = chr(97 + 25 - deg)
                            deg += 1
                        if matt[i][j] < 0:
                            sols[lead] += "+" + str(-matt[i][j]) + sols[j] + " "
                        else:
                            sols[lead] += str(-matt[i][j]) + sols[j] + " "
        for i in range(n):
            sols[i] = "x" + str(i + 1) + " = " + sols[i]
        return sols


# n = 3
# matt = []
# matt = np.random.randint(1, 100, (n, n + 1))
# matt = np.array([[1, 4, 7, 8], [0, 0, 0, 0], [0, 1, 0, 0]])
# matt = matt.astype(float)
n = int(input("Nhap so an: "))
matt = []

print("Nhap cac phan tu cua ma tran (nhap Enter de dung):")
while True:
    line = input()
    if line == "":
        break
    for val in line.split():
        matt.append(float(val))
while len(matt) < n * (n + 1):
    matt.append(0)
matt = np.array(matt).reshape((n, n + 1))
print(matt)
print(ToGauss_JordanForm(matt, n))
print(FindSolutions(matt, n))

Nhap cac phan tu cua ma tran (nhap Enter de dung):
[[ 1.  6.  4.  0.]
 [ 2.  4. -1.  0.]
 [-1.  2.  5.  0.]]
[[ 1.     0.    -2.75   0.   ]
 [ 0.     1.     1.125 -0.   ]
 [ 0.     0.     0.     0.   ]]
['x1 = 0.0 +2.75z ', 'x2 = -0.0 -1.125z ', 'x3 = z']


# Thuật toán Gauss-Jordan

Thuật toán Gauss-Jordan được sử dụng để giải hệ phương trình tuyến tính. Nó chuyển đổi ma trận hệ số của hệ phương trình thành dạng ma trận bậc thang rút gọn, từ đó tìm ra nghiệm của hệ.

## Các hàm trong thuật toán

1. `SwapRow(matt, i1, i2)`: Hàm này hoán đổi hai hàng `i1` và `i2` trong ma trận `matt`.

2. `FindNonZeroRow(matt, iRow, iColl)`: Hàm này tìm hàng đầu tiên từ `iRow` có phần tử khác không ở cột `iColl` trong ma trận `matt`.

3. `ToGauss_JordanForm(matt, n)`: Hàm này chuyển đổi ma trận `matt` thành dạng ma trận bậc thang rút gọn. Độ phức tạp của thuật toán này là O(N^3) cao hơn thuật toán khử Gauss thông thường, O(1/3 N^3). Thuật toán được cài đặt trong hàm này như sau (các chỉ sổ được đánh dấu từ 1 đến n hoặc n + 1): 

    - Bắt đầu với dòng nRow = 1 và cột nCol = 1, nếu như giá trị tại đó là 0 thì tìm hàng có chỉ số tại cùng cột nCol có giá trị khác không và hoán đổi 2 hàng với nhau. Nếu không tìm thấy, tăng chỉ số nCol và lặp lại bước này. Bước này tìm số đầu tiên khác 0 tại hàng trong ma trận bậc thang.
    - Khử hàng đó sao cho giá trị tại nRow và nCol là 1 (đưa dạng ma trận bậc thang rút gọn bằng cách chia tất cả phần tử của hàng cho giá trị đầu hàng khác không).
    - Duyệt tất cả các hàng còn lại, với mỗi lần duyệt khử từ cột nCol hiện tại đến cột cuối cùng (lấy giá trị của hàng được duyệt trừ cho k lần giá trị của hàng ở bước trên với k là giá trị hàng được duyệt và cột nCol).
    - Tăng chỉ số nCol và nRow và lặp lại bước 1.

4. `Rank(matt, rWall)`: Hàm này tính hạng của ma trận `matt`.

5. `FindSolutions(matt, n)`: Hàm này tìm nghiệm của hệ phương trình tuyến tính biểu diễn bởi ma trận `matt`. Hàm dựa vào ma trận đã được biến đổi thành dạng bậc thang rút gọn.

## Sử dụng thuật toán

Đầu tiên, khởi tạo ma trận `matt` biểu diễn hệ phương trình cần giải. Sau đó, gọi hàm `FindSolutions(matt, n)` để tìm nghiệm của hệ.
 
## Phân tích độ phức tạp của thuật toán
1. Độ phức tạp cho trường hợp xấu nhất (không có tồn tại 0 trong ma trận) là O(N^3).Duyệt n hàng mỗi lần duyệt, khử toàn bộ các hàng còn lại từ cột được duyệt. Gọi f(n) là các bước tính toán của hàm này.
    - f(n) = tổng từ i = 1 đến n của [n(n+2-i)] 
    - = n^2 * (n+2) - tổng từ 1 đến n 
    - = n^3 + 1.5n^2 - 0.5n
2. Với thuật toán Gauss, ở bước 3, thay vì duyệt tất cả các hàng ta chỉ duyệt các hàng ở dưới hàng hiện tại. Vậy f(n) của thuật Gauss là:
    - f(n) = tổng từ i = 1 đến n của [(n-i)(n+2-i)]
    - = tổng từ i = 1 đến n của [i*(i+2)]
    - = tổng từ i = 1 đến n của [i^2 + 2*i]
    - xấp xỉ : n(n+1)(2n+1)/6 thuộc O(1/3 N^3)